cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
   

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create')
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index),
    path('product_list', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

    path('questions_answer', views.questions_answer, name='questions_answer'),
    path('contact', views.contact, name='contact'),
]

cart/models.py
from django.db import models

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label="Кількість",choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    """Add Product to Cart View"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    """Remove Priduct from the Cart"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    """Cart View"""
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True,
        })
    return render(request, 'cart/detail.html', context={'cart': cart})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
Ваша корзина
{% endblock title %}

{% block content %}

<div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Кошик</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div class="px-5 ">
{% for msg in messages %}
    <div class="alert alert-success " role="alert">
        <strong class="d-flex justify-content-center"> {{ msg }} </strong>
    </div>
{% endfor %}
</div>


{% with total_items=cart|length %}
    {% if total_items > 0%}
        <div class="cart__info container-fluid pt-5">
            <div class="row px-xl-5">
                <div class="col-lg-8 table-responsive mb-5">
                    <table class="text-center mb-0">
                        <tbody class="align-middle ">
                            <h6>Кошик</h6>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr class="border-bottom border-top">
                                        <td class="align-middle bg-white py-4"><a href="{{ product.get_absolute_url }}">
                                            <img src="{% if product.image %}{{ product.image.url }}
                                            {% else %}{% static 'img/no_image.png' %}{% endif %}"
                                            alt="" style="width: 80px;"></a>
                                        </td>
                                        <td  class="align-middle bg-white">
                                            {{ product.name }}
                                        </td>
                                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                        <td class="align-middle bg-white">
                                            {{ item.update_quantity_form.quantity }}
                                            {{ item.update_quantity_form.override }}
                                        </td>
                                        <td class="align-middle bg-white">
                                            <button type="submit" class="btn btn-dark btn-sm" value="Update">Оновити</button>
                                            {% csrf_token %}
                                        </td>
                                        </form>
                                        <td class="align-middle bg-white">{{ item.total_price }} грн</td>
                                        <td class="align-middle bg-white">
                                            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                                <button type="submit" class="btn btn-dark btn-sm" value="delete">Видалити</button>
                                                {% csrf_token %}
                                            </form>
                                        </td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-4">
                    <div class="mb-5 ml-2">
                        <div class=" bg-white">
                            <h6 class="font-weight-semi-bold p-1  border-bottom">Дані замовлення</h6>
                        </div>
                        <div class="card-body bg-white">
                            <div class="d-flex justify-content-between mb-3 pt-1">
                                <h6 class="font-weight-medium">Сума</h6>
                                <h6 class="font-weight-medium">{{ cart.get_total_price }} грн</h6>
                            </div>
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium">Доставка</h6>
                                <h6 class="font-weight-medium">Безкоштовно</h6>
                            </div>
                        </div>
                        <div class="card-footer border-1 bg-white">
                            <div class="d-flex justify-content-between mt-2">
                                <h5 class="font-weight-bold">Загалом</h5>
                                <h5 class="font-weight-bold">{{ cart.get_total_price }} грн</h5>
                            </div>
                            {% with total_items=cart|length %}
                                {% if total_items > 0%}
                                    <a href="{% url 'orders:order_create' %}" class="btn btn-block btn-light my-3 py-3">Оформити замовлення</a>
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="empty_cart container-fluid p-5 border-top border-bottom">
            <div class="d-flex justify-content-center pb-2">
                <h5>Кошик порожній</h5>
            </div>
            <div class="d-flex justify-content-center">
                <a href="{% url 'shop:product_list' %}" class="btn essence-btn">Продовжити перегляд</a>
            </div>
        </div>
    {% endif %}
{% endwith %}
 
{% endblock content %}