cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
   

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index),
    path('product_list', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

    path('questions_answer', views.questions_answer, name='questions_answer'),
    path('contact', views.contact, name='contact'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    
class Product(models.Model):
    
     
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    trending = models.BooleanField(default=False, help_text="0=default, 1=Trending")


    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", kwargs={"id": self.id, "slug": self.slug})
    

class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.CharField(max_length=500)

shop/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.Form):
    first_name = forms.CharField(label="Ім'я",widget=forms.TextInput(attrs={"placeholder":"Ім'я","required":True,'class':'form-control'}),error_messages={"required":"Ім'я не може бути порожнім"})
    last_name = forms.CharField(label="Прізвище",widget=forms.TextInput(attrs={"placeholder":"Прізвище","required":True,'class':'form-control'}),error_messages={"required":"Прізвище не може бути порожнім"})
    email = forms.EmailField(label="E-mail",widget=forms.EmailInput(attrs={"required":True,"Placeholder":"E-mail",'class':'form-control'}),error_messages={'required':'Поля електронної пошти не повинні бути порожніми'})
    message = forms.CharField(min_length=20,label="Повідомлення", widget=forms.Textarea(attrs={'placeholder': 'Ваше повідомлення','class':'form-control'}))

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'message']

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages

from .models import Category, Product, Contact
from cart.forms import CartAddProductForm
from .forms import ContactForm
from django.views.generic import View
from django.http.response import HttpResponse, HttpResponseRedirect


def index(request):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    trending_products = Product.objects.filter(trending=1)
    return render(request, 'shop/index.html', context={
        'category': category,
        'categories': categories,
        'products': products,
        'trending_products': trending_products})

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render (request, 'shop/product/list.html', context={
        'category': category,
        'categories': categories,
        'products': products,
    })

def product_detail(request, id, slug):
    trending_products = Product.objects.filter(trending=1)
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    context = {'product':product,
               'cart_product_form':cart_product_form,
               'trending_products':trending_products}

    return render(request, 'shop/product/detail.html', context)



def questions_answer(request):
    return render(request, "shop/information/questions_answer.html")


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST or None)
        errors = None
        if form.is_valid():
            Contact.objects.create(
                first_name = form.cleaned_data.get('first_name'),
                last_name = form.cleaned_data.get('last_name'),
                email = form.cleaned_data.get('email'),
                message = form.cleaned_data.get('message')
                )
            messages.warning(request,"Запит на зворотний зв'язок надіслано. Очікуйте...")
            return render(request,"shop/information/contacts.html")
        if form.errors:
            errors = form.errors

        context = {'form':form, 'errors':errors}
        return render(request,"shop/information/contacts.html", context )
    else:
        form = ContactForm()

    return render(request, "shop/information/contacts.html", {'form':form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SPORT MANIA{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">


    <script defer src='https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js'></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" type="text/css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" type="text/css" rel="stylesheet" />
  

    <script type="text/javascript" src="{% static 'js/jquery-3.7.0.js' %} "></script>
    <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %} "></script>

   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="/">Sport<span>Mania</span></a></h1>
                    </div>
                </div>
                
                <div class="col-sm-6">
                    <div class="shopping-item">
                    {% with total_items=cart|length %}
                        <a href="{% url 'cart:cart_detail' %}">Кошик<i class="fa fa-shopping-cart"></i><span class="product-count">{{ total_items }}</span></a>
                    {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->
    
    <div class="mainmenu-area">
        <div id="subheader">
            <a class="subheader_item" href="/">Головна</a>
            <a class="subheader_item" href="{% url 'shop:contact' %}">Контакти</a>
            <a class="subheader_item" href="{% url 'shop:questions_answer' %}">Питання-відповіді</a>
            <a class="subheader_item" href="{% url 'shop:product_list' %}">Магазин</a>
        </div>
    </div>
</div>
    

<div>
    {% block content %}
    {% endblock content %}
</div>
<div>
    {% block index %}
    {% endblock index%}
</div>
<div>
    {% block product_list %}
    {% endblock product_list%}
</div>
<div>
    {% block about_us %}
    {% endblock about_us %}
</div>

</body>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}


{% block index %}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" type="text/css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>


<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'img/background-image.jpg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'img/background-image1.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'img/background-image2.jpg' %}" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="owl-carousel owl-theme product-list">
        {% for item in trending_products %}
            <div class="item pr-3 pt-4">
                <a href="{{ item.get_absolute_url }}">
                    <img src="{% if item.image %}
                        {{ item.image.url }}
                    {% else %}
                        {% static 'img/no_image.png' %}    
                    {% endif %}" alt="">
                </a>
                <a style="color:black;" href="{{ item.get_absolute_url}}">{{ item.name }}</a><br>
                    {{ item.price }} грн
            </div>
        {% endfor %}
    </div>
</div>







<script>
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
</script>
{% endblock index %}